name: PR Review Bot

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint (Check Syntax + Linting)
        id: eslint
        run: |
          OUTPUT=$(npx eslint . || true)
          echo "$OUTPUT" > eslint_output.txt
          echo "OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$OUTPUT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Analyze PR Changes
        id: pr_analysis
        run: |
          CHANGES=$(git diff --name-only origin/main)
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          echo "$CHANGES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment on PR
        uses: actions/github-script@v7
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('eslint_output.txt', 'utf8');
            const changedFiles = process.env.CHANGED_FILES;
            let commentBody = `### 🔍 PR Review Bot Report\n`;

            if (output.trim() !== '') {
              commentBody += `#### 🚨 Linting & Syntax Issues Found:\n\`\`\`\n${output}\n\`\`\`\n`;
            } else {
              commentBody += `✅ No linting or syntax errors found!\n`;
            }

            commentBody += `#### 📁 Changed Files:\n\`\`\`\n${changedFiles}\n\`\`\`\n`;
            commentBody += `⚡ **Tip for Reviewers:** Focus on key changes, large diffs, and logic improvements!`;

            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            });

      - name: Add PR Labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;
            const output = process.env.OUTPUT;

            let labels = ["ready-for-review"];
            if (output.trim() !== "") {
              labels.push("needs-fixes");
            }

            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: prNumber,
              labels
            });
